# Generated by Django 5.1.2 on 2024-10-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("portada", models.FileField(upload_to="portadas/")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo_seccion",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("imagen", "Imagen"),
                            ("video", "Video"),
                        ],
                        max_length=20,
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
                (
                    "pagina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secciones",
                        to="pagina.pagina",
                    ),
                ),
            ],
        ),
    ]
